#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNumaraları
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Okulnum")]
	public partial class OkulnoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBolumler(Bolumler instance);
    partial void UpdateBolumler(Bolumler instance);
    partial void DeleteBolumler(Bolumler instance);
    partial void InsertOgrenciler(OgrenciEkle instance);
    partial void UpdateOgrenciler(OgrenciEkle instance);
    partial void DeleteOgrenciler(OgrenciEkle instance);
    partial void InsertOkullar(Okullar instance);
    partial void UpdateOkullar(Okullar instance);
    partial void DeleteOkullar(Okullar instance);
    #endregion
		
		public OkulnoDataContext() : 
				base(global::OgrenciNumaraları.Properties.Settings.Default.OkulnumConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OkulnoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OkulnoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OkulnoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OkulnoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Bolumler> Bolumler
		{
			get
			{
				return this.GetTable<Bolumler>();
			}
		}
		
		public System.Data.Linq.Table<OgrenciEkle> Ogrenciler
		{
			get
			{
				return this.GetTable<OgrenciEkle>();
			}
		}
		
		public System.Data.Linq.Table<Okullar> Okullar
		{
			get
			{
				return this.GetTable<Okullar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bolumler")]
	public partial class Bolumler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OkulId;
		
		private int _BolumId;
		
		private string _BolumAdi;
		
		private EntitySet<OgrenciEkle> _Ogrenciler;
		
		private EntityRef<Okullar> _Okullar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOkulIdChanging(int value);
    partial void OnOkulIdChanged();
    partial void OnBolumIdChanging(int value);
    partial void OnBolumIdChanged();
    partial void OnBolumAdiChanging(string value);
    partial void OnBolumAdiChanged();
    #endregion
		
		public Bolumler()
		{
			this._Ogrenciler = new EntitySet<OgrenciEkle>(new Action<OgrenciEkle>(this.attach_Ogrenciler), new Action<OgrenciEkle>(this.detach_Ogrenciler));
			this._Okullar = default(EntityRef<Okullar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OkulId", DbType="Int NOT NULL")]
		public int OkulId
		{
			get
			{
				return this._OkulId;
			}
			set
			{
				if ((this._OkulId != value))
				{
					if (this._Okullar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOkulIdChanging(value);
					this.SendPropertyChanging();
					this._OkulId = value;
					this.SendPropertyChanged("OkulId");
					this.OnOkulIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BolumId
		{
			get
			{
				return this._BolumId;
			}
			set
			{
				if ((this._BolumId != value))
				{
					this.OnBolumIdChanging(value);
					this.SendPropertyChanging();
					this._BolumId = value;
					this.SendPropertyChanged("BolumId");
					this.OnBolumIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumAdi", DbType="NVarChar(50)")]
		public string BolumAdi
		{
			get
			{
				return this._BolumAdi;
			}
			set
			{
				if ((this._BolumAdi != value))
				{
					this.OnBolumAdiChanging(value);
					this.SendPropertyChanging();
					this._BolumAdi = value;
					this.SendPropertyChanged("BolumAdi");
					this.OnBolumAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bolumler_Ogrenciler", Storage="_Ogrenciler", ThisKey="BolumId", OtherKey="BolumId")]
		public EntitySet<OgrenciEkle> Ogrenciler
		{
			get
			{
				return this._Ogrenciler;
			}
			set
			{
				this._Ogrenciler.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Okullar_Bolumler", Storage="_Okullar", ThisKey="OkulId", OtherKey="OkulId", IsForeignKey=true)]
		public Okullar Okullar
		{
			get
			{
				return this._Okullar.Entity;
			}
			set
			{
				Okullar previousValue = this._Okullar.Entity;
				if (((previousValue != value) 
							|| (this._Okullar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Okullar.Entity = null;
						previousValue.Bolumler.Remove(this);
					}
					this._Okullar.Entity = value;
					if ((value != null))
					{
						value.Bolumler.Add(this);
						this._OkulId = value.OkulId;
					}
					else
					{
						this._OkulId = default(int);
					}
					this.SendPropertyChanged("Okullar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ogrenciler(OgrenciEkle entity)
		{
			this.SendPropertyChanging();
			entity.Bolumler = this;
		}
		
		private void detach_Ogrenciler(OgrenciEkle entity)
		{
			this.SendPropertyChanging();
			entity.Bolumler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ogrenciler")]
	public partial class OgrenciEkle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OkulId;
		
		private int _BolumId;
		
		private int _OgrenciId;
		
		private string _OgrenciAdi;
		
		private EntityRef<Bolumler> _Bolumler;
		
		private EntityRef<Okullar> _Okullar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOkulIdChanging(int value);
    partial void OnOkulIdChanged();
    partial void OnBolumIdChanging(int value);
    partial void OnBolumIdChanged();
    partial void OnOgrenciIdChanging(int value);
    partial void OnOgrenciIdChanged();
    partial void OnOgrenciAdiChanging(string value);
    partial void OnOgrenciAdiChanged();
    #endregion
		
		public OgrenciEkle()
		{
			this._Bolumler = default(EntityRef<Bolumler>);
			this._Okullar = default(EntityRef<Okullar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OkulId", DbType="Int NOT NULL")]
		public int OkulId
		{
			get
			{
				return this._OkulId;
			}
			set
			{
				if ((this._OkulId != value))
				{
					if (this._Okullar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOkulIdChanging(value);
					this.SendPropertyChanging();
					this._OkulId = value;
					this.SendPropertyChanged("OkulId");
					this.OnOkulIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumId", DbType="Int NOT NULL")]
		public int BolumId
		{
			get
			{
				return this._BolumId;
			}
			set
			{
				if ((this._BolumId != value))
				{
					if (this._Bolumler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBolumIdChanging(value);
					this.SendPropertyChanging();
					this._BolumId = value;
					this.SendPropertyChanged("BolumId");
					this.OnBolumIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int OgrenciId
		{
			get
			{
				return this._OgrenciId;
			}
			set
			{
				if ((this._OgrenciId != value))
				{
					this.OnOgrenciIdChanging(value);
					this.SendPropertyChanging();
					this._OgrenciId = value;
					this.SendPropertyChanged("OgrenciId");
					this.OnOgrenciIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OgrenciAdi
		{
			get
			{
				return this._OgrenciAdi;
			}
			set
			{
				if ((this._OgrenciAdi != value))
				{
					this.OnOgrenciAdiChanging(value);
					this.SendPropertyChanging();
					this._OgrenciAdi = value;
					this.SendPropertyChanged("OgrenciAdi");
					this.OnOgrenciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bolumler_Ogrenciler", Storage="_Bolumler", ThisKey="BolumId", OtherKey="BolumId", IsForeignKey=true)]
		public Bolumler Bolumler
		{
			get
			{
				return this._Bolumler.Entity;
			}
			set
			{
				Bolumler previousValue = this._Bolumler.Entity;
				if (((previousValue != value) 
							|| (this._Bolumler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Bolumler.Entity = null;
						previousValue.Ogrenciler.Remove(this);
					}
					this._Bolumler.Entity = value;
					if ((value != null))
					{
						value.Ogrenciler.Add(this);
						this._BolumId = value.BolumId;
					}
					else
					{
						this._BolumId = default(int);
					}
					this.SendPropertyChanged("Bolumler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Okullar_Ogrenciler", Storage="_Okullar", ThisKey="OkulId", OtherKey="OkulId", IsForeignKey=true)]
		public Okullar Okullar
		{
			get
			{
				return this._Okullar.Entity;
			}
			set
			{
				Okullar previousValue = this._Okullar.Entity;
				if (((previousValue != value) 
							|| (this._Okullar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Okullar.Entity = null;
						previousValue.Ogrenciler.Remove(this);
					}
					this._Okullar.Entity = value;
					if ((value != null))
					{
						value.Ogrenciler.Add(this);
						this._OkulId = value.OkulId;
					}
					else
					{
						this._OkulId = default(int);
					}
					this.SendPropertyChanged("Okullar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Okullar")]
	public partial class Okullar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OkulId;
		
		private string _OkulAdi;
		
		private EntitySet<Bolumler> _Bolumler;
		
		private EntitySet<OgrenciEkle> _Ogrenciler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOkulIdChanging(int value);
    partial void OnOkulIdChanged();
    partial void OnOkulAdiChanging(string value);
    partial void OnOkulAdiChanged();
    #endregion
		
		public Okullar()
		{
			this._Bolumler = new EntitySet<Bolumler>(new Action<Bolumler>(this.attach_Bolumler), new Action<Bolumler>(this.detach_Bolumler));
			this._Ogrenciler = new EntitySet<OgrenciEkle>(new Action<OgrenciEkle>(this.attach_Ogrenciler), new Action<OgrenciEkle>(this.detach_Ogrenciler));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OkulId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OkulId
		{
			get
			{
				return this._OkulId;
			}
			set
			{
				if ((this._OkulId != value))
				{
					this.OnOkulIdChanging(value);
					this.SendPropertyChanging();
					this._OkulId = value;
					this.SendPropertyChanged("OkulId");
					this.OnOkulIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OkulAdi", DbType="NVarChar(50)")]
		public string OkulAdi
		{
			get
			{
				return this._OkulAdi;
			}
			set
			{
				if ((this._OkulAdi != value))
				{
					this.OnOkulAdiChanging(value);
					this.SendPropertyChanging();
					this._OkulAdi = value;
					this.SendPropertyChanged("OkulAdi");
					this.OnOkulAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Okullar_Bolumler", Storage="_Bolumler", ThisKey="OkulId", OtherKey="OkulId")]
		public EntitySet<Bolumler> Bolumler
		{
			get
			{
				return this._Bolumler;
			}
			set
			{
				this._Bolumler.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Okullar_Ogrenciler", Storage="_Ogrenciler", ThisKey="OkulId", OtherKey="OkulId")]
		public EntitySet<OgrenciEkle> Ogrenciler
		{
			get
			{
				return this._Ogrenciler;
			}
			set
			{
				this._Ogrenciler.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Bolumler(Bolumler entity)
		{
			this.SendPropertyChanging();
			entity.Okullar = this;
		}
		
		private void detach_Bolumler(Bolumler entity)
		{
			this.SendPropertyChanging();
			entity.Okullar = null;
		}
		
		private void attach_Ogrenciler(OgrenciEkle entity)
		{
			this.SendPropertyChanging();
			entity.Okullar = this;
		}
		
		private void detach_Ogrenciler(OgrenciEkle entity)
		{
			this.SendPropertyChanging();
			entity.Okullar = null;
		}
	}
}
#pragma warning restore 1591
