#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uygulama2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="okul")]
	public partial class baglanti1 : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBolumler(Bolumler instance);
    partial void UpdateBolumler(Bolumler instance);
    partial void DeleteBolumler(Bolumler instance);
    partial void InsertOkullar(Okullar instance);
    partial void UpdateOkullar(Okullar instance);
    partial void DeleteOkullar(Okullar instance);
    #endregion
		
		public baglanti1() : 
				base(global::uygulama2.Properties.Settings.Default.okulConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public baglanti1(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public baglanti1(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public baglanti1(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public baglanti1(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Bolumler> Bolumler
		{
			get
			{
				return this.GetTable<Bolumler>();
			}
		}
		
		public System.Data.Linq.Table<Ogrenci> Ogrenci
		{
			get
			{
				return this.GetTable<Ogrenci>();
			}
		}
		
		public System.Data.Linq.Table<Okullar> Okullar
		{
			get
			{
				return this.GetTable<Okullar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bolumler")]
	public partial class Bolumler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _bolum_id;
		
		private string _bolum_ismi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbolum_idChanging(int value);
    partial void Onbolum_idChanged();
    partial void Onbolum_ismiChanging(string value);
    partial void Onbolum_ismiChanged();
    #endregion
		
		public Bolumler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bolum_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int bolum_id
		{
			get
			{
				return this._bolum_id;
			}
			set
			{
				if ((this._bolum_id != value))
				{
					this.Onbolum_idChanging(value);
					this.SendPropertyChanging();
					this._bolum_id = value;
					this.SendPropertyChanged("bolum_id");
					this.Onbolum_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bolum_ismi", DbType="NVarChar(50)")]
		public string bolum_ismi
		{
			get
			{
				return this._bolum_ismi;
			}
			set
			{
				if ((this._bolum_ismi != value))
				{
					this.Onbolum_ismiChanging(value);
					this.SendPropertyChanging();
					this._bolum_ismi = value;
					this.SendPropertyChanged("bolum_ismi");
					this.Onbolum_ismiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ogrenci")]
	public partial class Ogrenci
	{
		
		private int _okul_o_id;
		
		private int _bolum_o_id;
		
		private string _ogrenci_ad;
		
		private string _ogrenci_soyad;
		
		public Ogrenci()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_okul_o_id", DbType="Int NOT NULL")]
		public int okul_o_id
		{
			get
			{
				return this._okul_o_id;
			}
			set
			{
				if ((this._okul_o_id != value))
				{
					this._okul_o_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bolum_o_id", DbType="Int NOT NULL")]
		public int bolum_o_id
		{
			get
			{
				return this._bolum_o_id;
			}
			set
			{
				if ((this._bolum_o_id != value))
				{
					this._bolum_o_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ogrenci_ad", DbType="NVarChar(50)")]
		public string ogrenci_ad
		{
			get
			{
				return this._ogrenci_ad;
			}
			set
			{
				if ((this._ogrenci_ad != value))
				{
					this._ogrenci_ad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ogrenci_soyad", DbType="NVarChar(50)")]
		public string ogrenci_soyad
		{
			get
			{
				return this._ogrenci_soyad;
			}
			set
			{
				if ((this._ogrenci_soyad != value))
				{
					this._ogrenci_soyad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Okullar")]
	public partial class Okullar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _okul_id;
		
		private string _okul_adi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onokul_idChanging(int value);
    partial void Onokul_idChanged();
    partial void Onokul_adiChanging(string value);
    partial void Onokul_adiChanged();
    #endregion
		
		public Okullar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_okul_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int okul_id
		{
			get
			{
				return this._okul_id;
			}
			set
			{
				if ((this._okul_id != value))
				{
					this.Onokul_idChanging(value);
					this.SendPropertyChanging();
					this._okul_id = value;
					this.SendPropertyChanged("okul_id");
					this.Onokul_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_okul_adi", DbType="NVarChar(50)")]
		public string okul_adi
		{
			get
			{
				return this._okul_adi;
			}
			set
			{
				if ((this._okul_adi != value))
				{
					this.Onokul_adiChanging(value);
					this.SendPropertyChanging();
					this._okul_adi = value;
					this.SendPropertyChanged("okul_adi");
					this.Onokul_adiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
